import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";

export const extractResumeData = async (buffer) => {
  try {
    // Convert Node.js Buffer to Uint8Array
    const uint8Array = new Uint8Array(buffer);

    // Load PDF
    const pdf = await pdfjsLib.getDocument({ data: uint8Array }).promise;

    // Process all pages in parallel
    const pages = await Promise.all(
      Array.from({ length: pdf.numPages }, (_, i) => pdf.getPage(i + 1))
    );

    const pageTexts = await Promise.all(
      pages.map(async (page) => {
        const content = await page.getTextContent();
        return content.items.map((item) => item.str).join(" ");
      })
    );

    // Combine text from all pages
    const text = pageTexts.join("\n").toLowerCase();

    // Skills list
    const skillsList = [
      "javascript",
      "python",
      "java",
      "c++",
      "react",
      "node.js",
      "express",
      "mongodb",
      "sql",
      "html",
      "css",
      "aws",
      "docker",
      "kubernetes",
      "git",
      "linux",
      "machine learning",
      "data analysis",
      "tensorflow",
      "pandas",
      "numpy",
      "django",
      "flask",
      "angular",
      "vue.js",
      "ruby on rails",
      "php",
      "laravel",
      "swift",
      "kotlin",
      "flutter",
      "dart",
      "typescript",
      "graphql",
      "restful apis",
      "agile methodologies",
      "scrum",
      "devops",
      "ci/cd",
      "jupyter",
      "power bi",
      "tableau",
      "hadoop",
      "spark",
      "c#",
      "unity",
      "unreal engine",
      "blockchain",
      "solidity",
      "cybersecurity",
      "penetration testing",
      "networking",
      "virtualization",
      "vmware",
      "hyper-v",
      "big data",
      "cloud computing",
      "azure",
      "gcp",
      "salesforce",
      "jira",
      "confluence",
      "slack",
      "trello",
      "microsoft teams",
      "google workspace",
      "adobe creative suite",
      "photoshop",
      "illustrator",
      "after effects",
      "premiere pro",
      "autocad",
      "solidworks",
      "matlab",
      "r",
      "sas",
      "stata",
      "spss",
      "excel",
      "powerpoint",
      "word",
      "outlook",
      "sql server",
      "oracle",
      "mysql",
      "postgresql",
      "redis",
      "cassandra",
      "docker-compose",
      "ansible",
      "puppet",
      "chef",
      "jenkins",
      "circleci",
      "travisci",
      "prometheus",
      "grafana",
      "elasticsearch",
      "kibana",
      "logstash",
      "rabbitmq",
      "kafka",
      "zookeeper",
      "keras",
      "pytorch",
      "scikit-learn",
      "opencv",
      "nlp",
      "natural language processing",
    ];

    const foundSkills = skillsList.filter((skill) => text.includes(skill));

    // Cities list
    const possibleCities = [
      "indore",
      "bhopal",
      "gwalior",
      "ujjain",
      "jabalpur",
      "satna",
      "sagar",
      "ratlam",
      "dhar",
      "morena",
      "sehore",
      "vidisha",
      "rewa",
      "chhindwara",
      "burhanpur",
      "kishangarh",
      "mandleshwar",
      "delhi",
      "mumbai",
      "bangalore",
      "chennai",
      "hyderabad",
      "kolkata",
      "pune",
      "ahmedabad",
      "jaipur",
      "lucknow",
      "kanpur",
      "nagpur",
      "thane",
      "vadodara",
      "surat",
      "nashik",
      "faridabad",
      "meerut",
      "rajkot",
      "varanasi",
      "srinagar",
      "guntur",
      "agra",
      "allahabad",
      "coimbatore",
      "jodhpur",
      "salem",
      "tiruchirappalli",
      "mangalore",
      "dehradun",
      "mussoorie",
      "shimla",
      "manali",
      "goa",
      "udaipur",
      "jaisalmer",
      "rishikesh",
      "amritsar",
      "chandigarh",
      "gurgaon",
      "noida",
      "bhubaneswar",
      "vizag",
      "cuttack",
      "raipur",
      "bilaspur",
      "durg",
      "jamshedpur",
      "ranchi",
      "dhanbad",
      "asansol",
      "silchar",
      "imphal",
      "aizawl",
      "kohima",
      "gangtok",
      "itanagar",
      "dispur",
      "panaji",
    ];

    const location =
      possibleCities.find((city) => text.includes(city)) || "unknown";

    return { skills: foundSkills, location };
  } catch (error) {
    console.error("Error parsing resume:", error);
    throw error; // propagate error to controller
  }
};
